### ISSUE TITLE
为何我试了你的软件，不会自动更新？

### ISSUE THREAD

**Issue by auven** [sorrycc/test-release#1]
我下载了你这里的软件去试了一下，为什么它一直就是不会弹出提示框说更新？请大神指教一下，怎么才能实现你那个效果

**Comment by sorrycc** [comment]
下这个自然没用，这是 2.0 版本的，没有更加新的了。建议按照教程自行做一个。

**Comment by auven** [comment]
好的，谢谢你的指教，我研究研究去
